---
title: "Viet Map"
author: "Duc Du"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls(all.names = TRUE))
knitr::opts_chunk$set(echo = FALSE, 
                      cache=TRUE,
                      tidy.opts=list(width.cutoff=60),
                      tidy=TRUE)
#library(rmarkdown)
#library(knitr)
library(markdown)
library(stringr)
library(forcats)
library(RColorBrewer)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(Hmisc)
library(gtsummary)
#library(flextable)
library(huxtable)
library(data.table)
library(lubridate)
library(stringi)
library(forcats)
library(ggpubr)
library(rstatix)
#library(dlookr)
#library(flextable)
library(haven)
library(raster)
library(rgdal)
library(viridis)

# install.packages("sf")
# install.packages("terra")
# install.packages("spData")
# install.packages("spDataLarge", repos = "https://nowosad.r-universe.dev")

library(sf)          # classes and functions for vector data
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1; sf_use_s2() is TRUE
library(terra)       # classes and functions for raster data
library(spData)      # load geographic data
library(spDataLarge) # load larger geographic data
library(tmap)
library(leaflet)

select<-dplyr::select
filter<-dplyr::filter
recode<-dplyr::recode
getData<-raster::getData

# rotate function (see here: https://r-spatial.github.io/sf/articles/sf3.html#affine-transformations
rot <- function(a) matrix(c(cos(a), sin(a), -sin(a), cos(a)), 2, 2)

options(scipen=999, digits = 3)
options(max.print=1000000)
```

# Import libraries

```{r, message=FALSE, warning=FALSE}
#windowsFonts(georg = windowsFont('Georgia'))

# libraries we need
libs <- c("elevatr", "terra", "rayshader", "tidyverse", 
	"sf", "giscoR", "marmap", "jsonlite", "httr", "png")

# install missing libraries
installed_libs <- libs %in% rownames(installed.packages())
if (any(installed_libs == F)) {
  install.packages(libs[!installed_libs])
}

# load libraries
invisible(lapply(libs, library, character.only = T))
```

## Fetch the shapefile of Vietnam

```{r}
library(giscoR)
library(sf)
library(dplyr)

# 1. GET COUNTRY MAP
#---------

crsLONGLAT <- "+proj=longlat +datum=WGS84 +no_defs"

get_country_sf <- function(country_sf, country_transformed) {
	
	country_sf <- giscoR::gisco_get_countries(
    	year = "2016",
    	epsg = "4326",
    	resolution = "10",
    	country = "Vietnam")
	
	country_transformed <- st_transform(country_sf, crs = crsLONGLAT)

	return(country_transformed)
}

vietnam_transformed <- get_country_sf() 
```

## Import topographic data

```{r}
# 2. GET ELEVATION DATA
#----------------------

get_elevation_data <- function(country_elevation, country_elevation_df) {

	country_elevation <- get_elev_raster(
		locations = austria_transformed, 
		z = 7, 
		clip = "locations")

	elevation_mat <- raster_to_matrix(country_elevation)

	return(elevation_mat)
}

vietnam_dem <- get_elevation_data()
h <- 537
w <- 1552
```

## Retrieve overlay satellite imagery

```{r}
# 3. GET OVERLAY SATELLITE IMAGE
#----------------------

bb <- st_bbox(vietnam_transformed)
type <- "World_Imagery"
file <- NULL
height <- h*6
width <- w*6
crs_bb <- 4326

get_satellite_img <- function(url, params, res) {

  url <- parse_url("https://utility.arcgisonline.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task/execute")
  
  params <- list(
    baseMap = list(
      baseMapLayers = list(
        list(url = unbox("https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer"))
      )
    ),
    exportOptions = list(
      outputSize = c(width, height)
    ),
    mapOptions = list(
      extent = list(
        spatialReference = list(wkid = unbox(crs_bb)),
        xmax = unbox(bb["xmax"]),
        xmin = unbox(bb["xmin"]),
        ymax = unbox(bb["ymax"]),
        ymin = unbox(bb["ymin"])
      )
    )
  )
  
  res <- GET(
    url, 
    query = list(
      f = "json",
      Format = "PNG32",
      Layout_Template = "MAP_ONLY",
      Web_Map_as_JSON = toJSON(params))
  )

	return(res)

}

res <- get_satellite_img()
```

```{r}
write_map_png <- function(res_body, img_res, img_bin, file) {

	res_body <- content(res, type = "application/json")
	img_res <- GET(res_body$results[[1]]$value$url)
	img_bin <- content(img_res, "raw")
	file <- paste0(getwd(), "/vietnam_image.png")
	writeBin(img_bin, file)
}

write_map_png()
```

## Load the image into R using readPNG

```{r}
get_map_png <- function(img_file, vietnam_img) {
	
	img_file <- "vietnam_image.png"
	vietnam_img <- readPNG(img_file)

	return(vietnam_img)
}

vietnam_img <- get_map_png()
```

## 3D topographic map of Vietnam

```{r}
system('add-apt-repository -y ppa:cran/imagemagick')
system('apt-get update')
system("apt-get install libmagick++-dev")
install.packages("magick")
library(magick)
# 4. 3D MAP
#---------

vietnam_dem %>%
  sphere_shade(texture ="desert") %>%
  add_overlay(vietnam_img, alphalayer = .99) %>%
  plot_3d(vietnam_dem, 
	zscale = 15, 
	fov = 0, 
	theta = 0, 
	zoom = .55, 
	phi = 75,
	windowsize = c(1552, 537),
	background="black")
```




